import { CountryMetadata } from '../types';

export const COUNTRY_METADATA_MAP: Record<string, CountryMetadata> = {
  "Afghanistan": { name: "Afghanistan", iso2: "AF", iso3: "AFG", flagEmoji: "🇦🇫", capital: "Kabul", continent: "Asia", unRegion: "Southern Asia" },
  "Albania": { name: "Albania", iso2: "AL", iso3: "ALB", flagEmoji: "🇦🇱", capital: "Tirana", continent: "Europe", unRegion: "Southern Europe" },
  "Algeria": { name: "Algeria", iso2: "DZ", iso3: "DZA", flagEmoji: "🇩🇿", capital: "Algiers", continent: "Africa", unRegion: "Northern Africa" },
  "Andorra": { name: "Andorra", iso2: "AD", iso3: "AND", flagEmoji: "🇦🇩", capital: "Andorra la Vella", continent: "Europe", unRegion: "Southern Europe" },
  "Angola": { name: "Angola", iso2: "AO", iso3: "AGO", flagEmoji: "🇦🇴", capital: "Luanda", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Antigua and Barbuda": { name: "Antigua and Barbuda", iso2: "AG", iso3: "ATG", flagEmoji: "🇦🇬", capital: "St. John's", continent: "Americas", unRegion: "Caribbean" },
  "Argentina": { name: "Argentina", iso2: "AR", iso3: "ARG", flagEmoji: "🇦🇷", capital: "Buenos Aires", continent: "Americas", unRegion: "South America" },
  "Armenia": { name: "Armenia", iso2: "AM", iso3: "ARM", flagEmoji: "🇦🇲", capital: "Yerevan", continent: "Asia", unRegion: "Western Asia" },
  "Australia": { name: "Australia", iso2: "AU", iso3: "AUS", flagEmoji: "🇦🇺", capital: "Canberra", continent: "Oceania", unRegion: "Australia and New Zealand" },
  "Austria": { name: "Austria", iso2: "AT", iso3: "AUT", flagEmoji: "🇦🇹", capital: "Vienna", continent: "Europe", unRegion: "Western Europe" },
  "Azerbaijan": { name: "Azerbaijan", iso2: "AZ", iso3: "AZE", flagEmoji: "🇦🇿", capital: "Baku", continent: "Asia", unRegion: "Western Asia" },
  "Bahamas": { name: "Bahamas", iso2: "BS", iso3: "BHS", flagEmoji: "🇧🇸", capital: "Nassau", continent: "Americas", unRegion: "Caribbean" },
  "Bahrain": { name: "Bahrain", iso2: "BH", iso3: "BHR", flagEmoji: "🇧🇭", capital: "Manama", continent: "Asia", unRegion: "Western Asia" },
  "Bangladesh": { name: "Bangladesh", iso2: "BD", iso3: "BGD", flagEmoji: "🇧🇩", capital: "Dhaka", continent: "Asia", unRegion: "Southern Asia" },
  "Barbados": { name: "Barbados", iso2: "BB", iso3: "BRB", flagEmoji: "🇧🇧", capital: "Bridgetown", continent: "Americas", unRegion: "Caribbean" },
  "Belarus": { name: "Belarus", iso2: "BY", iso3: "BLR", flagEmoji: "🇧🇾", capital: "Minsk", continent: "Europe", unRegion: "Eastern Europe" },
  "Belgium": { name: "Belgium", iso2: "BE", iso3: "BEL", flagEmoji: "🇧🇪", capital: "Brussels", continent: "Europe", unRegion: "Western Europe" },
  "Belize": { name: "Belize", iso2: "BZ", iso3: "BLZ", flagEmoji: "🇧🇿", capital: "Belmopan", continent: "Americas", unRegion: "Central America" },
  "Benin": { name: "Benin", iso2: "BJ", iso3: "BEN", flagEmoji: "🇧🇯", capital: "Porto-Novo", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Bhutan": { name: "Bhutan", iso2: "BT", iso3: "BTN", flagEmoji: "🇧🇹", capital: "Thimphu", continent: "Asia", unRegion: "Southern Asia" },
  "Bolivia": { name: "Bolivia", iso2: "BO", iso3: "BOL", flagEmoji: "🇧🇴", capital: "Sucre", continent: "Americas", unRegion: "South America" },
  "Bosnia and Herzegovina": { name: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH", flagEmoji: "🇧🇦", capital: "Sarajevo", continent: "Europe", unRegion: "Southern Europe" },
  "Botswana": { name: "Botswana", iso2: "BW", iso3: "BWA", flagEmoji: "🇧🇼", capital: "Gaborone", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Brazil": { name: "Brazil", iso2: "BR", iso3: "BRA", flagEmoji: "🇧🇷", capital: "Brasília", continent: "Americas", unRegion: "South America" },
  "Brunei": { name: "Brunei", iso2: "BN", iso3: "BRN", flagEmoji: "🇧🇳", capital: "Bandar Seri Begawan", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Bulgaria": { name: "Bulgaria", iso2: "BG", iso3: "BGR", flagEmoji: "🇧🇬", capital: "Sofia", continent: "Europe", unRegion: "Eastern Europe" },
  "Burkina Faso": { name: "Burkina Faso", iso2: "BF", iso3: "BFA", flagEmoji: "🇧🇫", capital: "Ouagadougou", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Burundi": { name: "Burundi", iso2: "BI", iso3: "BDI", flagEmoji: "🇧🇮", capital: "Gitega", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Cambodia": { name: "Cambodia", iso2: "KH", iso3: "KHM", flagEmoji: "🇰🇭", capital: "Phnom Penh", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Cameroon": { name: "Cameroon", iso2: "CM", iso3: "CMR", flagEmoji: "🇨🇲", capital: "Yaoundé", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Canada": { name: "Canada", iso2: "CA", iso3: "CAN", flagEmoji: "🇨🇦", capital: "Ottawa", continent: "Americas", unRegion: "Northern America" },
  "Cape Verde": { name: "Cape Verde", iso2: "CV", iso3: "CPV", flagEmoji: "🇨🇻", capital: "Praia", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Central African Republic": { name: "Central African Republic", iso2: "CF", iso3: "CAF", flagEmoji: "🇨🇫", capital: "Bangui", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Chad": { name: "Chad", iso2: "TD", iso3: "TCD", flagEmoji: "🇹🇩", capital: "N'Djamena", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Chile": { name: "Chile", iso2: "CL", iso3: "CHL", flagEmoji: "🇨🇱", capital: "Santiago", continent: "Americas", unRegion: "South America" },
  "China": { name: "China", iso2: "CN", iso3: "CHN", flagEmoji: "🇨🇳", capital: "Beijing", continent: "Asia", unRegion: "Eastern Asia" },
  "Colombia": { name: "Colombia", iso2: "CO", iso3: "COL", flagEmoji: "🇨🇴", capital: "Bogotá", continent: "Americas", unRegion: "South America" },
  "Comoros": { name: "Comoros", iso2: "KM", iso3: "COM", flagEmoji: "🇰🇲", capital: "Moroni", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Congo": { name: "Congo", iso2: "CG", iso3: "COG", flagEmoji: "🇨🇬", capital: "Brazzaville", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Congo (Dem. Rep.)": { name: "Congo (Dem. Rep.)", iso2: "CD", iso3: "COD", flagEmoji: "🇨🇩", capital: "Kinshasa", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Costa Rica": { name: "Costa Rica", iso2: "CR", iso3: "CRI", flagEmoji: "🇨🇷", capital: "San José", continent: "Americas", unRegion: "Central America" },
  "Cote d'Ivoire": { name: "Cote d'Ivoire", iso2: "CI", iso3: "CIV", flagEmoji: "🇨🇮", capital: "Yamoussoukro", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Croatia": { name: "Croatia", iso2: "HR", iso3: "HRV", flagEmoji: "🇭🇷", capital: "Zagreb", continent: "Europe", unRegion: "Southern Europe" },
  "Cuba": { name: "Cuba", iso2: "CU", iso3: "CUB", flagEmoji: "🇨🇺", capital: "Havana", continent: "Americas", unRegion: "Caribbean" },
  "Cyprus": { name: "Cyprus", iso2: "CY", iso3: "CYP", flagEmoji: "🇨🇾", capital: "Nicosia", continent: "Europe", unRegion: "Southern Europe" },
  "Czech Republic": { name: "Czech Republic", iso2: "CZ", iso3: "CZE", flagEmoji: "🇨🇿", capital: "Prague", continent: "Europe", unRegion: "Eastern Europe" },
  "Czechia": { name: "Czechia", iso2: "CZ", iso3: "CZE", flagEmoji: "🇨🇿", capital: "Prague", continent: "Europe", unRegion: "Eastern Europe" },
  "Denmark": { name: "Denmark", iso2: "DK", iso3: "DNK", flagEmoji: "🇩🇰", capital: "Copenhagen", continent: "Europe", unRegion: "Northern Europe" },
  "Djibouti": { name: "Djibouti", iso2: "DJ", iso3: "DJI", flagEmoji: "🇩🇯", capital: "Djibouti", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Dominica": { name: "Dominica", iso2: "DM", iso3: "DMA", flagEmoji: "🇩🇲", capital: "Roseau", continent: "Americas", unRegion: "Caribbean" },
  "Dominican Republic": { name: "Dominican Republic", iso2: "DO", iso3: "DOM", flagEmoji: "🇩🇴", capital: "Santo Domingo", continent: "Americas", unRegion: "Caribbean" },
  "Ecuador": { name: "Ecuador", iso2: "EC", iso3: "ECU", flagEmoji: "🇪🇨", capital: "Quito", continent: "Americas", unRegion: "South America" },
  "Egypt": { name: "Egypt", iso2: "EG", iso3: "EGY", flagEmoji: "🇪🇬", capital: "Cairo", continent: "Africa", unRegion: "Northern Africa" },
  "El Salvador": { name: "El Salvador", iso2: "SV", iso3: "SLV", flagEmoji: "🇸🇻", capital: "San Salvador", continent: "Americas", unRegion: "Central America" },
  "Equatorial Guinea": { name: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ", flagEmoji: "🇬🇶", capital: "Malabo", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Eritrea": { name: "Eritrea", iso2: "ER", iso3: "ERI", flagEmoji: "🇪🇷", capital: "Asmara", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Estonia": { name: "Estonia", iso2: "EE", iso3: "EST", flagEmoji: "🇪🇪", capital: "Tallinn", continent: "Europe", unRegion: "Northern Europe" },
  "Eswatini": { name: "Eswatini", iso2: "SZ", iso3: "SWZ", flagEmoji: "🇸🇿", capital: "Mbabane", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Ethiopia": { name: "Ethiopia", iso2: "ET", iso3: "ETH", flagEmoji: "🇪🇹", capital: "Addis Ababa", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Fiji": { name: "Fiji", iso2: "FJ", iso3: "FJI", flagEmoji: "🇫🇯", capital: "Suva", continent: "Oceania", unRegion: "Melanesia" },
  "Finland": { name: "Finland", iso2: "FI", iso3: "FIN", flagEmoji: "🇫🇮", capital: "Helsinki", continent: "Europe", unRegion: "Northern Europe" },
  "France": { name: "France", iso2: "FR", iso3: "FRA", flagEmoji: "🇫🇷", capital: "Paris", continent: "Europe", unRegion: "Western Europe" },
  "Gabon": { name: "Gabon", iso2: "GA", iso3: "GAB", flagEmoji: "🇬🇦", capital: "Libreville", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Gambia": { name: "Gambia", iso2: "GM", iso3: "GMB", flagEmoji: "🇬🇲", capital: "Banjul", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Georgia": { name: "Georgia", iso2: "GE", iso3: "GEO", flagEmoji: "🇬🇪", capital: "Tbilisi", continent: "Asia", unRegion: "Western Asia" },
  "Germany": { name: "Germany", iso2: "DE", iso3: "DEU", flagEmoji: "🇩🇪", capital: "Berlin", continent: "Europe", unRegion: "Western Europe" },
  "Ghana": { name: "Ghana", iso2: "GH", iso3: "GHA", flagEmoji: "🇬🇭", capital: "Accra", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Greece": { name: "Greece", iso2: "GR", iso3: "GRC", flagEmoji: "🇬🇷", capital: "Athens", continent: "Europe", unRegion: "Southern Europe" },
  "Grenada": { name: "Grenada", iso2: "GD", iso3: "GRD", flagEmoji: "🇬🇩", capital: "St. George's", continent: "Americas", unRegion: "Caribbean" },
  "Guatemala": { name: "Guatemala", iso2: "GT", iso3: "GTM", flagEmoji: "🇬🇹", capital: "Guatemala City", continent: "Americas", unRegion: "Central America" },
  "Guinea": { name: "Guinea", iso2: "GN", iso3: "GIN", flagEmoji: "🇬🇳", capital: "Conakry", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Guinea-Bissau": { name: "Guinea-Bissau", iso2: "GW", iso3: "GNB", flagEmoji: "🇬🇼", capital: "Bissau", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Guyana": { name: "Guyana", iso2: "GY", iso3: "GUY", flagEmoji: "🇬🇾", capital: "Georgetown", continent: "Americas", unRegion: "South America" },
  "Haiti": { name: "Haiti", iso2: "HT", iso3: "HTI", flagEmoji: "🇭🇹", capital: "Port-au-Prince", continent: "Americas", unRegion: "Caribbean" },
  "Honduras": { name: "Honduras", iso2: "HN", iso3: "HND", flagEmoji: "🇭🇳", capital: "Tegucigalpa", continent: "Americas", unRegion: "Central America" },
  "Hong Kong": { name: "Hong Kong", iso2: "HK", iso3: "HKG", flagEmoji: "🇭🇰", capital: "Hong Kong", continent: "Asia", unRegion: "Eastern Asia" },
  "Hungary": { name: "Hungary", iso2: "HU", iso3: "HUN", flagEmoji: "🇭🇺", capital: "Budapest", continent: "Europe", unRegion: "Eastern Europe" },
  "Iceland": { name: "Iceland", iso2: "IS", iso3: "ISL", flagEmoji: "🇮🇸", capital: "Reykjavík", continent: "Europe", unRegion: "Northern Europe" },
  "India": { name: "India", iso2: "IN", iso3: "IND", flagEmoji: "🇮🇳", capital: "New Delhi", continent: "Asia", unRegion: "Southern Asia" },
  "Indonesia": { name: "Indonesia", iso2: "ID", iso3: "IDN", flagEmoji: "🇮🇩", capital: "Jakarta", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Iran": { name: "Iran", iso2: "IR", iso3: "IRN", flagEmoji: "🇮🇷", capital: "Tehran", continent: "Asia", unRegion: "Southern Asia" },
  "Iraq": { name: "Iraq", iso2: "IQ", iso3: "IRQ", flagEmoji: "🇮🇶", capital: "Baghdad", continent: "Asia", unRegion: "Western Asia" },
  "Ireland": { name: "Ireland", iso2: "IE", iso3: "IRL", flagEmoji: "🇮🇪", capital: "Dublin", continent: "Europe", unRegion: "Northern Europe" },
  "Israel": { name: "Israel", iso2: "IL", iso3: "ISR", flagEmoji: "🇮🇱", capital: "Jerusalem", continent: "Asia", unRegion: "Western Asia" },
  "Italy": { name: "Italy", iso2: "IT", iso3: "ITA", flagEmoji: "🇮🇹", capital: "Rome", continent: "Europe", unRegion: "Southern Europe" },
  "Jamaica": { name: "Jamaica", iso2: "JM", iso3: "JAM", flagEmoji: "🇯🇲", capital: "Kingston", continent: "Americas", unRegion: "Caribbean" },
  "Japan": { name: "Japan", iso2: "JP", iso3: "JPN", flagEmoji: "🇯🇵", capital: "Tokyo", continent: "Asia", unRegion: "Eastern Asia" },
  "Jordan": { name: "Jordan", iso2: "JO", iso3: "JOR", flagEmoji: "🇯🇴", capital: "Amman", continent: "Asia", unRegion: "Western Asia" },
  "Kazakhstan": { name: "Kazakhstan", iso2: "KZ", iso3: "KAZ", flagEmoji: "🇰🇿", capital: "Astana", continent: "Asia", unRegion: "Central Asia" },
  "Kenya": { name: "Kenya", iso2: "KE", iso3: "KEN", flagEmoji: "🇰🇪", capital: "Nairobi", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Kiribati": { name: "Kiribati", iso2: "KI", iso3: "KIR", flagEmoji: "🇰🇮", capital: "South Tarawa", continent: "Oceania", unRegion: "Micronesia" },
  "Kosovo": { name: "Kosovo", iso2: "XK", iso3: "XKX", flagEmoji: "🇽🇰", capital: "Pristina", continent: "Europe", unRegion: "Southern Europe" },
  "Kuwait": { name: "Kuwait", iso2: "KW", iso3: "KWT", flagEmoji: "🇰🇼", capital: "Kuwait City", continent: "Asia", unRegion: "Western Asia" },
  "Kyrgyzstan": { name: "Kyrgyzstan", iso2: "KG", iso3: "KGZ", flagEmoji: "🇰🇬", capital: "Bishkek", continent: "Asia", unRegion: "Central Asia" },
  "Laos": { name: "Laos", iso2: "LA", iso3: "LAO", flagEmoji: "🇱🇦", capital: "Vientiane", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Latvia": { name: "Latvia", iso2: "LV", iso3: "LVA", flagEmoji: "🇱🇻", capital: "Riga", continent: "Europe", unRegion: "Northern Europe" },
  "Lebanon": { name: "Lebanon", iso2: "LB", iso3: "LBN", flagEmoji: "🇱🇧", capital: "Beirut", continent: "Asia", unRegion: "Western Asia" },
  "Lesotho": { name: "Lesotho", iso2: "LS", iso3: "LSO", flagEmoji: "🇱🇸", capital: "Maseru", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Liberia": { name: "Liberia", iso2: "LR", iso3: "LBR", flagEmoji: "🇱🇷", capital: "Monrovia", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Libya": { name: "Libya", iso2: "LY", iso3: "LBY", flagEmoji: "🇱🇾", capital: "Tripoli", continent: "Africa", unRegion: "Northern Africa" },
  "Liechtenstein": { name: "Liechtenstein", iso2: "LI", iso3: "LIE", flagEmoji: "🇱🇮", capital: "Vaduz", continent: "Europe", unRegion: "Western Europe" },
  "Lithuania": { name: "Lithuania", iso2: "LT", iso3: "LTU", flagEmoji: "🇱🇹", capital: "Vilnius", continent: "Europe", unRegion: "Northern Europe" },
  "Luxembourg": { name: "Luxembourg", iso2: "LU", iso3: "LUX", flagEmoji: "🇱🇺", capital: "Luxembourg City", continent: "Europe", unRegion: "Western Europe" },
  "Macao": { name: "Macao", iso2: "MO", iso3: "MAC", flagEmoji: "🇲🇴", capital: "Macao", continent: "Asia", unRegion: "Eastern Asia" },
  "Madagascar": { name: "Madagascar", iso2: "MG", iso3: "MDG", flagEmoji: "🇲🇬", capital: "Antananarivo", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Malawi": { name: "Malawi", iso2: "MW", iso3: "MWI", flagEmoji: "🇲🇼", capital: "Lilongwe", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Malaysia": { name: "Malaysia", iso2: "MY", iso3: "MYS", flagEmoji: "🇲🇾", capital: "Kuala Lumpur", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Maldives": { name: "Maldives", iso2: "MV", iso3: "MDV", flagEmoji: "🇲🇻", capital: "Malé", continent: "Asia", unRegion: "Southern Asia" },
  "Mali": { name: "Mali", iso2: "ML", iso3: "MLI", flagEmoji: "🇲🇱", capital: "Bamako", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Malta": { name: "Malta", iso2: "MT", iso3: "MLT", flagEmoji: "🇲🇹", capital: "Valletta", continent: "Europe", unRegion: "Southern Europe" },
  "Marshall Islands": { name: "Marshall Islands", iso2: "MH", iso3: "MHL", flagEmoji: "🇲🇭", capital: "Majuro", continent: "Oceania", unRegion: "Micronesia" },
  "Mauritania": { name: "Mauritania", iso2: "MR", iso3: "MRT", flagEmoji: "🇲🇷", capital: "Nouakchott", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Mauritius": { name: "Mauritius", iso2: "MU", iso3: "MUS", flagEmoji: "🇲🇺", capital: "Port Louis", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Mexico": { name: "Mexico", iso2: "MX", iso3: "MEX", flagEmoji: "🇲🇽", capital: "Mexico City", continent: "Americas", unRegion: "Central America" },
  "Micronesia": { name: "Micronesia", iso2: "FM", iso3: "FSM", flagEmoji: "🇫🇲", capital: "Palikir", continent: "Oceania", unRegion: "Micronesia" },
  "Moldova": { name: "Moldova", iso2: "MD", iso3: "MDA", flagEmoji: "🇲🇩", capital: "Chișinău", continent: "Europe", unRegion: "Eastern Europe" },
  "Monaco": { name: "Monaco", iso2: "MC", iso3: "MCO", flagEmoji: "🇲🇨", capital: "Monaco", continent: "Europe", unRegion: "Western Europe" },
  "Mongolia": { name: "Mongolia", iso2: "MN", iso3: "MNG", flagEmoji: "🇲🇳", capital: "Ulaanbaatar", continent: "Asia", unRegion: "Eastern Asia" },
  "Montenegro": { name: "Montenegro", iso2: "ME", iso3: "MNE", flagEmoji: "🇲🇪", capital: "Podgorica", continent: "Europe", unRegion: "Southern Europe" },
  "Morocco": { name: "Morocco", iso2: "MA", iso3: "MAR", flagEmoji: "🇲🇦", capital: "Rabat", continent: "Africa", unRegion: "Northern Africa" },
  "Mozambique": { name: "Mozambique", iso2: "MZ", iso3: "MOZ", flagEmoji: "🇲🇿", capital: "Maputo", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Myanmar": { name: "Myanmar", iso2: "MM", iso3: "MMR", flagEmoji: "🇲🇲", capital: "Naypyidaw", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Namibia": { name: "Namibia", iso2: "NA", iso3: "NAM", flagEmoji: "🇳🇦", capital: "Windhoek", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Nauru": { name: "Nauru", iso2: "NR", iso3: "NRU", flagEmoji: "🇳🇷", capital: "Yaren", continent: "Oceania", unRegion: "Micronesia" },
  "Nepal": { name: "Nepal", iso2: "NP", iso3: "NPL", flagEmoji: "🇳🇵", capital: "Kathmandu", continent: "Asia", unRegion: "Southern Asia" },
  "Netherlands": { name: "Netherlands", iso2: "NL", iso3: "NLD", flagEmoji: "🇳🇱", capital: "Amsterdam", continent: "Europe", unRegion: "Western Europe" },
  "New Zealand": { name: "New Zealand", iso2: "NZ", iso3: "NZL", flagEmoji: "🇳🇿", capital: "Wellington", continent: "Oceania", unRegion: "Australia and New Zealand" },
  "Nicaragua": { name: "Nicaragua", iso2: "NI", iso3: "NIC", flagEmoji: "🇳🇮", capital: "Managua", continent: "Americas", unRegion: "Central America" },
  "Niger": { name: "Niger", iso2: "NE", iso3: "NER", flagEmoji: "🇳🇪", capital: "Niamey", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Nigeria": { name: "Nigeria", iso2: "NG", iso3: "NGA", flagEmoji: "🇳🇬", capital: "Abuja", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "North Korea": { name: "North Korea", iso2: "KP", iso3: "PRK", flagEmoji: "🇰🇵", capital: "Pyongyang", continent: "Asia", unRegion: "Eastern Asia" },
  "North Macedonia": { name: "North Macedonia", iso2: "MK", iso3: "MKD", flagEmoji: "🇲🇰", capital: "Skopje", continent: "Europe", unRegion: "Southern Europe" },
  "Norway": { name: "Norway", iso2: "NO", iso3: "NOR", flagEmoji: "🇳🇴", capital: "Oslo", continent: "Europe", unRegion: "Northern Europe" },
  "Oman": { name: "Oman", iso2: "OM", iso3: "OMN", flagEmoji: "🇴🇲", capital: "Muscat", continent: "Asia", unRegion: "Western Asia" },
  "Pakistan": { name: "Pakistan", iso2: "PK", iso3: "PAK", flagEmoji: "🇵🇰", capital: "Islamabad", continent: "Asia", unRegion: "Southern Asia" },
  "Palau": { name: "Palau", iso2: "PW", iso3: "PLW", flagEmoji: "🇵🇼", capital: "Ngerulmud", continent: "Oceania", unRegion: "Micronesia" },
  "Palestinian Territory": { name: "Palestinian Territory", iso2: "PS", iso3: "PSE", flagEmoji: "🇵🇸", capital: "Ramallah", continent: "Asia", unRegion: "Western Asia" },
  "Panama": { name: "Panama", iso2: "PA", iso3: "PAN", flagEmoji: "🇵🇦", capital: "Panama City", continent: "Americas", unRegion: "Central America" },
  "Papua New Guinea": { name: "Papua New Guinea", iso2: "PG", iso3: "PNG", flagEmoji: "🇵🇬", capital: "Port Moresby", continent: "Oceania", unRegion: "Melanesia" },
  "Paraguay": { name: "Paraguay", iso2: "PY", iso3: "PRY", flagEmoji: "🇵🇾", capital: "Asunción", continent: "Americas", unRegion: "South America" },
  "Peru": { name: "Peru", iso2: "PE", iso3: "PER", flagEmoji: "🇵🇪", capital: "Lima", continent: "Americas", unRegion: "South America" },
  "Philippines": { name: "Philippines", iso2: "PH", iso3: "PHL", flagEmoji: "🇵🇭", capital: "Manila", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Poland": { name: "Poland", iso2: "PL", iso3: "POL", flagEmoji: "🇵🇱", capital: "Warsaw", continent: "Europe", unRegion: "Eastern Europe" },
  "Portugal": { name: "Portugal", iso2: "PT", iso3: "PRT", flagEmoji: "🇵🇹", capital: "Lisbon", continent: "Europe", unRegion: "Southern Europe" },
  "Qatar": { name: "Qatar", iso2: "QA", iso3: "QAT", flagEmoji: "🇶🇦", capital: "Doha", continent: "Asia", unRegion: "Western Asia" },
  "Romania": { name: "Romania", iso2: "RO", iso3: "ROU", flagEmoji: "🇷🇴", capital: "Bucharest", continent: "Europe", unRegion: "Eastern Europe" },
  "Russia": { name: "Russia", iso2: "RU", iso3: "RUS", flagEmoji: "🇷🇺", capital: "Moscow", continent: "Europe", unRegion: "Eastern Europe" },
  "Rwanda": { name: "Rwanda", iso2: "RW", iso3: "RWA", flagEmoji: "🇷🇼", capital: "Kigali", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Saint Kitts and Nevis": { name: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA", flagEmoji: "🇰🇳", capital: "Basseterre", continent: "Americas", unRegion: "Caribbean" },
  "Saint Lucia": { name: "Saint Lucia", iso2: "LC", iso3: "LCA", flagEmoji: "🇱🇨", capital: "Castries", continent: "Americas", unRegion: "Caribbean" },
  "Samoa": { name: "Samoa", iso2: "WS", iso3: "WSM", flagEmoji: "🇼🇸", capital: "Apia", continent: "Oceania", unRegion: "Polynesia" },
  "San Marino": { name: "San Marino", iso2: "SM", iso3: "SMR", flagEmoji: "🇸🇲", capital: "San Marino", continent: "Europe", unRegion: "Southern Europe" },
  "Sao Tome and Principe": { name: "Sao Tome and Principe", iso2: "ST", iso3: "STP", flagEmoji: "🇸🇹", capital: "São Tomé", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Saudi Arabia": { name: "Saudi Arabia", iso2: "SA", iso3: "SAU", flagEmoji: "🇸🇦", capital: "Riyadh", continent: "Asia", unRegion: "Western Asia" },
  "Senegal": { name: "Senegal", iso2: "SN", iso3: "SEN", flagEmoji: "🇸🇳", capital: "Dakar", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Serbia": { name: "Serbia", iso2: "RS", iso3: "SRB", flagEmoji: "🇷🇸", capital: "Belgrade", continent: "Europe", unRegion: "Southern Europe" },
  "Seychelles": { name: "Seychelles", iso2: "SC", iso3: "SYC", flagEmoji: "🇸🇨", capital: "Victoria", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Sierra Leone": { name: "Sierra Leone", iso2: "SL", iso3: "SLE", flagEmoji: "🇸🇱", capital: "Freetown", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Singapore": { name: "Singapore", iso2: "SG", iso3: "SGP", flagEmoji: "🇸🇬", capital: "Singapore", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Slovakia": { name: "Slovakia", iso2: "SK", iso3: "SVK", flagEmoji: "🇸🇰", capital: "Bratislava", continent: "Europe", unRegion: "Eastern Europe" },
  "Slovenia": { name: "Slovenia", iso2: "SI", iso3: "SVN", flagEmoji: "🇸🇮", capital: "Ljubljana", continent: "Europe", unRegion: "Southern Europe" },
  "Solomon Islands": { name: "Solomon Islands", iso2: "SB", iso3: "SLB", flagEmoji: "🇸🇧", capital: "Honiara", continent: "Oceania", unRegion: "Melanesia" },
  "Somalia": { name: "Somalia", iso2: "SO", iso3: "SOM", flagEmoji: "🇸🇴", capital: "Mogadishu", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "South Africa": { name: "South Africa", iso2: "ZA", iso3: "ZAF", flagEmoji: "🇿🇦", capital: "Pretoria", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "South Korea": { name: "South Korea", iso2: "KR", iso3: "KOR", flagEmoji: "🇰🇷", capital: "Seoul", continent: "Asia", unRegion: "Eastern Asia" },
  "South Sudan": { name: "South Sudan", iso2: "SS", iso3: "SSD", flagEmoji: "🇸🇸", capital: "Juba", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Spain": { name: "Spain", iso2: "ES", iso3: "ESP", flagEmoji: "🇪🇸", capital: "Madrid", continent: "Europe", unRegion: "Southern Europe" },
  "Sri Lanka": { name: "Sri Lanka", iso2: "LK", iso3: "LKA", flagEmoji: "🇱🇰", capital: "Sri Jayawardenepura Kotte", continent: "Asia", unRegion: "Southern Asia" },
  "Sudan": { name: "Sudan", iso2: "SD", iso3: "SDN", flagEmoji: "🇸🇩", capital: "Khartoum", continent: "Africa", unRegion: "Northern Africa" },
  "Suriname": { name: "Suriname", iso2: "SR", iso3: "SUR", flagEmoji: "🇸🇷", capital: "Paramaribo", continent: "Americas", unRegion: "South America" },
  "Sweden": { name: "Sweden", iso2: "SE", iso3: "SWE", flagEmoji: "🇸🇪", capital: "Stockholm", continent: "Europe", unRegion: "Northern Europe" },
  "Switzerland": { name: "Switzerland", iso2: "CH", iso3: "CHE", flagEmoji: "🇨🇭", capital: "Bern", continent: "Europe", unRegion: "Western Europe" },
  "Syria": { name: "Syria", iso2: "SY", iso3: "SYR", flagEmoji: "🇸🇾", capital: "Damascus", continent: "Asia", unRegion: "Western Asia" },
  "Taiwan": { name: "Taiwan", iso2: "TW", iso3: "TWN", flagEmoji: "🇹🇼", capital: "Taipei", continent: "Asia", unRegion: "Eastern Asia" },
  "Tajikistan": { name: "Tajikistan", iso2: "TJ", iso3: "TJK", flagEmoji: "🇹🇯", capital: "Dushanbe", continent: "Asia", unRegion: "Central Asia" },
  "Tanzania": { name: "Tanzania", iso2: "TZ", iso3: "TZA", flagEmoji: "🇹🇿", capital: "Dodoma", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Thailand": { name: "Thailand", iso2: "TH", iso3: "THA", flagEmoji: "🇹🇭", capital: "Bangkok", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Timor-Leste": { name: "Timor-Leste", iso2: "TL", iso3: "TLS", flagEmoji: "🇹🇱", capital: "Dili", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Togo": { name: "Togo", iso2: "TG", iso3: "TGO", flagEmoji: "🇹🇬", capital: "Lomé", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Tonga": { name: "Tonga", iso2: "TO", iso3: "TON", flagEmoji: "🇹🇴", capital: "Nuku'alofa", continent: "Oceania", unRegion: "Polynesia" },
  "Trinidad and Tobago": { name: "Trinidad and Tobago", iso2: "TT", iso3: "TTO", flagEmoji: "🇹🇹", capital: "Port of Spain", continent: "Americas", unRegion: "Caribbean" },
  "Tunisia": { name: "Tunisia", iso2: "TN", iso3: "TUN", flagEmoji: "🇹🇳", capital: "Tunis", continent: "Africa", unRegion: "Northern Africa" },
  "Turkey": { name: "Turkey", iso2: "TR", iso3: "TUR", flagEmoji: "🇹🇷", capital: "Ankara", continent: "Asia", unRegion: "Western Asia" },
  "Turkmenistan": { name: "Turkmenistan", iso2: "TM", iso3: "TKM", flagEmoji: "🇹🇲", capital: "Ashgabat", continent: "Asia", unRegion: "Central Asia" },
  "Tuvalu": { name: "Tuvalu", iso2: "TV", iso3: "TUV", flagEmoji: "🇹🇻", capital: "Funafuti", continent: "Oceania", unRegion: "Polynesia" },
  "Uganda": { name: "Uganda", iso2: "UG", iso3: "UGA", flagEmoji: "🇺🇬", capital: "Kampala", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Ukraine": { name: "Ukraine", iso2: "UA", iso3: "UKR", flagEmoji: "🇺🇦", capital: "Kyiv", continent: "Europe", unRegion: "Eastern Europe" },
  "United Arab Emirates": { name: "United Arab Emirates", iso2: "AE", iso3: "ARE", flagEmoji: "🇦🇪", capital: "Abu Dhabi", continent: "Asia", unRegion: "Western Asia" },
  "United Kingdom": { name: "United Kingdom", iso2: "GB", iso3: "GBR", flagEmoji: "🇬🇧", capital: "London", continent: "Europe", unRegion: "Northern Europe" },
  "United States": { name: "United States", iso2: "US", iso3: "USA", flagEmoji: "🇺🇸", capital: "Washington, D.C.", continent: "Americas", unRegion: "Northern America" },
  "Uruguay": { name: "Uruguay", iso2: "UY", iso3: "URY", flagEmoji: "🇺🇾", capital: "Montevideo", continent: "Americas", unRegion: "South America" },
  "Uzbekistan": { name: "Uzbekistan", iso2: "UZ", iso3: "UZB", flagEmoji: "🇺🇿", capital: "Tashkent", continent: "Asia", unRegion: "Central Asia" },
  "Vanuatu": { name: "Vanuatu", iso2: "VU", iso3: "VUT", flagEmoji: "🇻🇺", capital: "Port Vila", continent: "Oceania", unRegion: "Melanesia" },
  "Vatican City": { name: "Vatican City", iso2: "VA", iso3: "VAT", flagEmoji: "🇻🇦", capital: "Vatican City", continent: "Europe", unRegion: "Southern Europe" },
  "Venezuela": { name: "Venezuela", iso2: "VE", iso3: "VEN", flagEmoji: "🇻🇪", capital: "Caracas", continent: "Americas", unRegion: "South America" },
  "Vietnam": { name: "Vietnam", iso2: "VN", iso3: "VNM", flagEmoji: "🇻🇳", capital: "Hanoi", continent: "Asia", unRegion: "South-Eastern Asia" },
  "Yemen": { name: "Yemen", iso2: "YE", iso3: "YEM", flagEmoji: "🇾🇪", capital: "Sana'a", continent: "Asia", unRegion: "Western Asia" },
  "Zambia": { name: "Zambia", iso2: "ZM", iso3: "ZMB", flagEmoji: "🇿🇲", capital: "Lusaka", continent: "Africa", unRegion: "Sub-Saharan Africa" },
  "Zimbabwe": { name: "Zimbabwe", iso2: "ZW", iso3: "ZWE", flagEmoji: "🇿🇼", capital: "Harare", continent: "Africa", unRegion: "Sub-Saharan Africa" }
};

export const DEFAULT_COUNTRY_METADATA: CountryMetadata = {
  name: "Unknown",
  iso2: "UN",
  iso3: "UNK",
  flagEmoji: "🌐",
  capital: "Unknown",
  continent: "Other",
  unRegion: "Other"
};

export function getCountryMetadata(countryName: string): CountryMetadata {
  if (COUNTRY_METADATA_MAP[countryName]) {
    return COUNTRY_METADATA_MAP[countryName];
  }
  // Try case-insensitive or partial match fallback
  const normalized = countryName.trim().toLowerCase();
  for (const key of Object.keys(COUNTRY_METADATA_MAP)) {
    if (key.toLowerCase() === normalized) {
      return COUNTRY_METADATA_MAP[key];
    }
  }
  return { ...DEFAULT_COUNTRY_METADATA, name: countryName };
}
